main_path: ./Nextcloud/Programming/
projects:
  static site:
    path: Webdevelopment/
    cmd: git clone https://github.com/SaracenRhue/HTML-boilerplate.git pro_name
  nodejs:
    path: Webdevelopment/
    cmd: mkdir pro_name && cd pro_name && touch app.js && npm init -y
  react:
    path: Webdevelopment/React/
    cmd: npx create-react-app pro_name
  electron:
    path: electron/
    cmd: npx create-electron-app@latest pro_name
  docker:
    path: docker/
    cmd: mkdir pro_name && cd pro_name && touch Dockerfile && touch .dockerignore
  python:
    path: Python/
    cmd: mkdir pro_name && cd pro_name && touch main.py
  bash:
    path: bash/
    cmd: mkdir pro_name && cd pro_name && touch script.sh && echo "#!/bin/bash" >> script.sh
  cpp:
    path: cpp/
    cmd: git clone https://github.com/SaracenRhue/cpp-boilerplate.git pro_name
  jekyll:
    path: jekyll/
    cmd: jekyll new pro_name && cd pro_name && bundle update --bundler && bundle add webrick && bundle install --redownload && code . && bundle exec jekyll serve

